# run: conda env create --file environment.yml
name: C:\Users\yingdingwang\Documents\VENV\gpt3.12conda
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
# use libuv==1.39 for windows
# acording to the torch page https://pypi.org/project/torch/
dependencies:
- python==3.12
- libuv==1.48.0
- libjpeg-turbo
- libpng 
- pip>=24.2
- pip:
  # works for regular pip packages
  # - docx
  # and for wheels
  # a lot will be installed due to dependency to applyllm
  - torch==2.7.0
  - torchvision==0.22.0
  - torchaudio==2.7.0
  - --index-url https://download.pytorch.org/whl/xpu
  - intel-extension-for-pytorch==2.7.10+xpu
  - --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/xpu/us/
  - -r requirements_winx64_conda.txt