# run: conda env create --file environment.yml
name: C:\Users\yingdingwang\Documents\VENV\gpt3.12conda
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
# use libuv==1.39 for windows
# acording to the torch page https://pypi.org/project/torch/
dependencies:
- python==3.12
- libuv==1.48.0
- libjpeg-turbo
- libpng 
- pip>=24.2
- pip:
  # works for regular pip packages
  # - docx
  # and for wheels
  # a lot will be installed due to dependency to applyllm
  - -r requirements_winx64_conda.txt